### ISSUE TITLE
Window open

### ISSUE THREAD

**Issue by Draygv2** [TA2k/ioBroker.velux#11]
Could somebody implement the function that i can open the window? Or is the API blocking that?

**Comment by Draygv2** [comment]
It is always red if i do so

**Comment by nemodil** [comment]
Hi,
All of my Velux shutters works fine with target_position :-)
Log entry: {"status":"ok","time_server":16374*****}
But for my Velux windows, only target_position 0 has an effect, ie the windows are closed.
All other values has no effect and results with an error.
Log entry: {"status":"ok","time_server":16374.....,"body":{"home":{"id":"5eb3e9cf3fc5e9**********"},"errors":[{"code":9,"id":"563613**********"}]}}
Is this is a Velux security setting, that they don't allow to open wondows this way?
Do you have a solution for this problem?

**Comment by TA2k** [comment]
Yes opening needs a pairing with the router.
An idea is to add the windows in homekit and use the new homekit adapter
https://forum.iobroker.net/topic/48570/test-alpha-homekit-controller-0-0-x

**Comment by nemodil** [comment]
Thanks for your answer!
I’ll be looking at this homekit-controller adapter, because pairing with the router isn't an option, is it?

**Comment by TA2k** [comment]
I dont have a router and was not able to see the traffic

**Comment by Draygv2** [comment]
I connected the Velux direct to the iobroker with the homekitadapter and everything works fine. Now I us homekit for window movments and velux for the rest.

**Comment by jotrax** [comment]
When using the Homekit-Adapter, will it also work (for windows and blinds), when the Velux-Gateway has no internet access?

**Comment by Draygv2** [comment]
No it won't. Velux need internet for no reason.

**Comment by jotrax** [comment]
I gave it a try yesterday. After 5-6 attempts I could pair the gateway with homekit. Then I cut the internet connection from the velux gateway, which I could verify by checking with the velux active app saying "connection to gateway lost". I was still able to control windows with homekit adapter. Today morning I power cycled the gateway since I need to move it to another place and afterwards no homekit connection was possible, unless the device answered my ping requests. When I allowed internet connection via firewall for a few minutes the gateway was available on homekit again.
